export const login_path = '/login'
export const veterinarios_all = '/veterinarios'
export const veterinarios_create = '/veterinarios/new'
export const veterinarios_update = '/veterinarios/update'
export const productos_all = '/productos'
export const citas_agendar = '/citas/new'
export const ver_cita = '/citas'
