export const login_path = '/login'
export const veterinarios_all = '/veterinarios'
export const veterinarios_create = '/veterinarios/new'
export const veterinarios_update = '/veterinarios/update'
export const veterinarios_agenda = '/agenda'
export const cita = '/citas/'
export const cita_ver = 'ver/'
export const cita_diagnostico = 'agregarDiagnostico'
export const cita_delete = 'delete/'
export const cita_update = '/update'

